Api Class Reference
Public Member Functions
index ($format='JSON')
Additional Inherited Members
Detailed Description
Definition at line 2 of file Api.php.
Member Function Documentation
index()
index ($format = 'JSON')
Definition at line 3 of file Api.php.
References Redirect\controller(), BaseController\convert(), BaseController\loadModel(), BaseController\scrape(), and Auth\user().
                                            {
        $user = $this->loadModel('Users');
        $user = Auth::user();
        if ($user) {
            $html = $this->scrape('GET', '
      https://www.bedrebegravelse.dk/424/bedemand-priser-paa-begravelse-eller-bisaettelse');
            $html = $html->find('#divPreview > .fourth');
            
            foreach ($html as $value) {
                $products[] = ['typePrice' => $value->find('p', 0)->plaintext, 'description' => $value->
      find('a', 0)->title, 'image' => 'https://www.bedrebegravelse.dk/' . $value->find('img', 0)->src];
            }
            echo $this->convert($format, $products);
        }
        else {
            Redirect::controller('Login@index');
        }
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/controllers/Api.php