simple_html_dom Class Reference
Public Member Functions
__construct ($str=null, $lowercase=true, $forceTagsClosed=true, $target_charset=DEFAULT_TARGET_CHARSET, $stripRN=true, $defaultBRText=DEFAULT_BR_TEXT, $defaultSpanText=DEFAULT_SPAN_TEXT)
__destruct ()
load ($str, $lowercase=true, $stripRN=true, $defaultBRText=DEFAULT_BR_TEXT, $defaultSpanText=DEFAULT_SPAN_TEXT)
load_file ()
set_callback ($function_name)
remove_callback ()
save ($filepath='')
find ($selector, $idx=null, $lowercase=false)
clear ()
dump ($show_attr=true)
restore_noise ($text)
search_noise ($text)
__toString ()
__get ($name)
childNodes ($idx=-1)
firstChild ()
lastChild ()
createElement ($name, $value=null)
createTextNode ($value)
getElementById ($id)
getElementsById ($id, $idx=null)
getElementByTagName ($name)
getElementsByTagName ($name, $idx=-1)
loadFile ()
Data Fields
$root = null
$nodes = array()
$callback = null
$lowercase = false
$original_size
$size
$_charset = ''
$_target_charset = ''
$default_span_text = ``
Protected Member Functions
prepare ($str, $lowercase=true, $stripRN=true, $defaultBRText=DEFAULT_BR_TEXT, $defaultSpanText=DEFAULT_SPAN_TEXT)
parse ()
parse_charset ()
read_tag ()
parse_attr ($node, $name, &$space)
link_nodes (&$node, $is_child)
as_text_node ($tag)
skip ($chars)
copy_skip ($chars)
copy_until ($chars)
copy_until_char ($char)
copy_until_char_escape ($char)
remove_noise ($pattern, $remove_tag=false)
Protected Attributes
$pos
$doc
$char
$cursor
$parent
$noise = array()
$token_blank = ` \t\r\n`
$token_equal = ' =/>'
$token_slash = ` />\r\n\t`
$token_attr = ' >'
$default_br_text = ``
$self_closing_tags = array('img'=>1, 'br'=>1, 'input'=>1, 'meta'=>1, 'link'=>1, 'hr'=>1, 'base'=>1, 'embed'=>1, 'spacer'=>1)
$block_tags = array('root'=>1, 'body'=>1, 'form'=>1, 'div'=>1, 'span'=>1, 'table'=>1)
$optional_closing_tags
Detailed Description
Definition at line 971 of file simple_html_dom.php.
Constructor & Destructor Documentation
__construct()
__construct ($str = null, $lowercase = true, $forceTagsClosed = true, $target_charset = DEFAULT_TARGET_CHARSET, $stripRN = true, $defaultBRText = DEFAULT_BR_TEXT, $defaultSpanText = DEFAULT_SPAN_TEXT)
Definition at line 1015 of file simple_html_dom.php.
    {
        if ($str)
        {
            if (preg_match("/^http:\/\//i",$str) || is_file($str))
            {
                $this->load_file($str);
            }
            else
            {
                $this->load($str, $lowercase, $stripRN, $defaultBRText, $defaultSpanText);
            }
        }
        // Forcing tags to be closed implies that we don't trust the html, but it can lead to parsing
       errors if we SHOULD trust the html.
        if (!$forceTagsClosed) {
            $this->optional_closing_array=array();
        }
        $this->_target_charset = $target_charset;
    }
__destruct()
__destruct ()
Definition at line 1035 of file simple_html_dom.php.
References simple_html_dom_node\clear().
    {
        $this->clear();
    }
Member Function Documentation
__get()
__get ($name)
Definition at line 1691 of file simple_html_dom.php.
    {
        switch ($name)
        {
            case 'outertext':
                return $this->root->innertext();
            case 'innertext':
                return $this->root->innertext();
            case 'plaintext':
                return $this->root->text();
            case 'charset':
                return $this->_charset;
            case 'target_charset':
                return $this->_target_charset;
        }
    }
__toString()
__toString ()
Definition at line 1686 of file simple_html_dom.php.
    {
        return $this->root->innertext();
    }
as_text_node()
as_text_node ($tag) [protected]
Definition at line 1531 of file simple_html_dom.php.
References simple_html_dom_node\$tag, and HDOM_INFO_TEXT.
    {
        $node = new simple_html_dom_node($this);
        ++$this->cursor;
        $node->_[HDOM_INFO_TEXT] = '</' . $tag . '>';
        $this->link_nodes($node, false);
        $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
        return true;
    }
childNodes()
childNodes ($idx = -1)
Definition at line 1709 of file simple_html_dom.php.
{return $this->root->childNodes($idx);}
clear()
clear ()
Definition at line 1117 of file simple_html_dom.php.
References simple_html_dom_node\children(), and simple_html_dom_node\parent().
    {
        foreach ($this->nodes as $n) {$n->clear(); $n = null;}
        // This add next line is documented in the sourceforge repository. 2977248 as a fix for ongoing
       memory leaks that occur even with the use of clear.
        if (isset($this->children)) foreach ($this->children as $n) {$n->clear(); $n = null;}
        if (isset($this->parent)) {$this->parent->clear(); unset($this->parent);}
        if (isset($this->root)) {$this->root->clear(); unset($this->root);}
        unset($this->doc);
        unset($this->noise);
    }
copy_skip()
copy_skip ($chars) [protected]
Definition at line 1547 of file simple_html_dom.php.
    {
        $pos = $this->pos;
        $len = strspn($this->doc, $chars, $pos);
        $this->pos += $len;
        $this->char = ($this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
        if ($len===0) return '';
        return substr($this->doc, $pos, $len);
    }
copy_until()
copy_until ($chars) [protected]
Definition at line 1557 of file simple_html_dom.php.
    {
        $pos = $this->pos;
        $len = strcspn($this->doc, $chars, $pos);
        $this->pos += $len;
        $this->char = ($this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
        return substr($this->doc, $pos, $len);
    }
copy_until_char()
copy_until_char ($char) [protected]
Definition at line 1566 of file simple_html_dom.php.
    {
        if ($this->char===null) return '';
        if (($pos = strpos($this->doc, $char, $this->pos))===false) {
            $ret = substr($this->doc, $this->pos, $this->size-$this->pos);
            $this->char = null;
            $this->pos = $this->size;
            return $ret;
        }
        if ($pos===$this->pos) return '';
        $pos_old = $this->pos;
        $this->char = $this->doc[$pos];
        $this->pos = $pos;
        return substr($this->doc, $pos_old, $pos-$pos_old);
    }
copy_until_char_escape()
copy_until_char_escape ($char) [protected]
Definition at line 1584 of file simple_html_dom.php.
    {
        if ($this->char===null) return '';
        $start = $this->pos;
        while (1)
        {
            if (($pos = strpos($this->doc, $char, $start))===false)
            {
                $ret = substr($this->doc, $this->pos, $this->size-$this->pos);
                $this->char = null;
                $this->pos = $this->size;
                return $ret;
            }
            if ($pos===$this->pos) return '';
            if ($this->doc[$pos-1]==='\\') {
                $start = $pos+1;
                continue;
            }
            $pos_old = $this->pos;
            $this->char = $this->doc[$pos];
            $this->pos = $pos;
            return substr($this->doc, $pos_old, $pos-$pos_old);
        }
    }
createElement()
createElement ($name, $value = null)
Definition at line 1712 of file simple_html_dom.php.
References str_get_html().
{return @str_get_html("<$name>$value</$name>")->first_child();}
createTextNode()
createTextNode ($value)
Definition at line 1713 of file simple_html_dom.php.
References str_get_html().
{return @end(str_get_html($value)->nodes);}
dump()
dump ($show_attr = true)
Definition at line 1128 of file simple_html_dom.php.
    {
        $this->root->dump($show_attr);
    }
find()
find ($selector, $idx = null, $lowercase = false)
Definition at line 1111 of file simple_html_dom.php.
    {
        return $this->root->find($selector, $idx, $lowercase);
    }
firstChild()
firstChild ()
Definition at line 1710 of file simple_html_dom.php.
{return $this->root->first_child();}
getElementById()
getElementById ($id)
Definition at line 1714 of file simple_html_dom.php.
References simple_html_dom_node\find().
{return $this->find("#$id", 0);}
getElementByTagName()
getElementByTagName ($name)
Definition at line 1716 of file simple_html_dom.php.
References simple_html_dom_node\find().
{return $this->find($name, 0);}
getElementsById()
getElementsById ($id, $idx = null)
Definition at line 1715 of file simple_html_dom.php.
References simple_html_dom_node\find().
{return $this->find("#$id", $idx);}
getElementsByTagName()
getElementsByTagName ($name, $idx = -1)
Definition at line 1717 of file simple_html_dom.php.
References simple_html_dom_node\find().
{return $this->find($name, $idx);}
lastChild()
lastChild ()
Definition at line 1711 of file simple_html_dom.php.
{return $this->root->last_child();}
link_nodes()
link_nodes (& $node, $is_child) [protected]
Definition at line 1520 of file simple_html_dom.php.
References simple_html_dom_node\$parent, and simple_html_dom_node\parent().
    {
        $node->parent = $this->parent;
        $this->parent->nodes[] = $node;
        if ($is_child)
        {
            $this->parent->children[] = $node;
        }
    }
load()
load ($str, $lowercase = true, $stripRN = true, $defaultBRText = DEFAULT_BR_TEXT, $defaultSpanText = DEFAULT_SPAN_TEXT)
Definition at line 1041 of file simple_html_dom.php.
References HDOM_INFO_END.
    {
        global $debugObject;
        // prepare
        $this->prepare($str, $lowercase, $stripRN, $defaultBRText, $defaultSpanText);
        // strip out comments
        $this->remove_noise("'<!--(.*?)-->'is");
        // strip out cdata
        $this->remove_noise("'<!\[CDATA\[(.*?)\]\]>'is", true);
        // Per sourceforge
       http://sourceforge.net/tracker/?func=detail&aid=2949097&group_id=218559&atid=1044037
        // Script tags removal now preceeds style tag removal.
        // strip out <script> tags
        $this->remove_noise("'<\s*script[^>]*[^/]>(.*?)<\s*/\s*script\s*>'is");
        $this->remove_noise("'<\s*script\s*>(.*?)<\s*/\s*script\s*>'is");
        // strip out <style> tags
        $this->remove_noise("'<\s*style[^>]*[^/]>(.*?)<\s*/\s*style\s*>'is");
        $this->remove_noise("'<\s*style\s*>(.*?)<\s*/\s*style\s*>'is");
        // strip out preformatted tags
        $this->remove_noise("'<\s*(?:code)[^>]*>(.*?)<\s*/\s*(?:code)\s*>'is");
        // strip out server side scripts
        $this->remove_noise("'(<\?)(.*?)(\?>)'s", true);
        // strip smarty scripts
        $this->remove_noise("'(\{\w)(.*?)(\})'s", true);
        // parsing
        while ($this->parse());
        // end
        $this->root->_[HDOM_INFO_END] = $this->cursor;
        $this->parse_charset();
        // make load function chainable
        return $this;
    }
load_file()
load_file ()
Definition at line 1078 of file simple_html_dom.php.
References simple_html_dom_node\clear().
    {
        $args = func_get_args();
        $this->load(call_user_func_array('file_get_contents', $args), true);
        // Throw an error if we can't properly load the dom.
        if (($error=error_get_last())!==null) {
            $this->clear();
            return false;
        }
    }
loadFile()
loadFile ()
Definition at line 1718 of file simple_html_dom.php.
{$args = func_get_args();$this->load_file($args);}
parse()
parse () [protected]
Definition at line 1169 of file simple_html_dom.php.
References HDOM_INFO_TEXT.
    {
        if (($s = $this->copy_until_char('<'))==='')
        {
            return $this->read_tag();
        }
        // text
        $node = new simple_html_dom_node($this);
        ++$this->cursor;
        $node->_[HDOM_INFO_TEXT] = $s;
        $this->link_nodes($node, false);
        return true;
    }
parse_attr()
parse_attr ($node, $name, & $space) [protected]
Definition at line 1483 of file simple_html_dom.php.
References HDOM_INFO_QUOTE, HDOM_QUOTE_DOUBLE, HDOM_QUOTE_NO, and HDOM_QUOTE_SINGLE.
    {
        // Per sourceforge:
       http://sourceforge.net/tracker/?func=detail&aid=3061408&group_id=218559&atid=1044037
        // If the attribute is already defined inside a tag, only pay atetntion to the first one as opposed
       to the last one.
        if (isset($node->attr[$name]))
        {
            return;
        }
        $space[2] = $this->copy_skip($this->token_blank);
        switch ($this->char) {
            case '"':
                $node->_[HDOM_INFO_QUOTE][] = HDOM_QUOTE_DOUBLE;
                $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; //
       next
                $node->attr[$name] = $this->restore_noise($this->
      copy_until_char_escape('"'));
                $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; //
       next
                break;
            case '\'':
                $node->_[HDOM_INFO_QUOTE][] = HDOM_QUOTE_SINGLE;
                $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; //
       next
                $node->attr[$name] = $this->restore_noise($this->
      copy_until_char_escape('\''));
                $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; //
       next
                break;
            default:
                $node->_[HDOM_INFO_QUOTE][] = HDOM_QUOTE_NO;
                $node->attr[$name] = $this->restore_noise($this->
      copy_until($this->token_attr));
        }
        // PaperG: Attributes should not have \r or \n in them, that counts as html whitespace.
        $node->attr[$name] = str_replace("\r", "", $node->attr[$name]);
        $node->attr[$name] = str_replace("\n", "", $node->attr[$name]);
        // PaperG: If this is a "class" selector, lets get rid of the preceeding and trailing space since
       some people leave it in the multi class case.
        if ($name == "class") {
            $node->attr[$name] = trim($node->attr[$name]);
        }
    }
parse_charset()
parse_charset () [protected]
Definition at line 1187 of file simple_html_dom.php.
    {
        global $debugObject;
        $charset = null;
        if (function_exists('get_last_retrieve_url_contents_content_type'))
        {
            $contentTypeHeader = get_last_retrieve_url_contents_content_type();
            $success = preg_match('/charset=(.+)/', $contentTypeHeader, $matches);
            if ($success)
            {
                $charset = $matches[1];
                if (is_object($debugObject)) {$debugObject->debugLog(2, 'header content-type found charset
       of: ' . $charset);}
            }
        }
        if (empty($charset))
        {
            $el = $this->root->find('meta[http-equiv=Content-Type]',0);
            if (!empty($el))
            {
                $fullvalue = $el->content;
                if (is_object($debugObject)) {$debugObject->debugLog(2, 'meta content-type tag found' .
      $fullvalue);}
                if (!empty($fullvalue))
                {
                    $success = preg_match('/charset=(.+)/', $fullvalue, $matches);
                    if ($success)
                    {
                        $charset = $matches[1];
                    }
                    else
                    {
                        // If there is a meta tag, and they don't specify the character set, research says
       that it's typically ISO-8859-1
                        if (is_object($debugObject)) {$debugObject->debugLog(2, 'meta content-type tag
       couldn\'t be parsed. using iso-8859 default.');}
                        $charset = 'ISO-8859-1';
                    }
                }
            }
        }
        // If we couldn't find a charset above, then lets try to detect one based on the text we got...
        if (empty($charset))
        {
            // Have php try to detect the encoding from the text given to us.
            $charset = mb_detect_encoding($this->root->plaintext . "ascii", $encoding_list = array("UTF-8"
      , "CP1252"));
            if (is_object($debugObject)) {$debugObject->debugLog(2, 'mb_detect found: ' . $charset);}
            // and if this doesn't work... then we need to just wrongheadedly assume it's UTF-8 so that we
       can move on - cause this will usually give us most of what we need...
            if ($charset === false)
            {
                if (is_object($debugObject)) {$debugObject->debugLog(2, 'since mb_detect failed - using
       default of utf-8');}
                $charset = 'UTF-8';
            }
        }
        // Since CP1252 is a superset, if we get one of it's subsets, we want it instead.
        if ((strtolower($charset) == strtolower('ISO-8859-1')) || (strtolower($charset) == strtolower('
      Latin1')) || (strtolower($charset) == strtolower('Latin-1')))
        {
            if (is_object($debugObject)) {$debugObject->debugLog(2, 'replacing ' . $charset . ' with CP1252
       as its a superset');}
            $charset = 'CP1252';
        }
        if (is_object($debugObject)) {$debugObject->debugLog(1, 'EXIT - ' . $charset);}
        return $this->_charset = $charset;
    }
prepare()
prepare ($str, $lowercase = true, $stripRN = true, $defaultBRText = DEFAULT_BR_TEXT, $defaultSpanText = DEFAULT_SPAN_TEXT) [protected]
Definition at line 1134 of file simple_html_dom.php.
References simple_html_dom_node\clear(), HDOM_INFO_BEGIN, HDOM_TYPE_ROOT, and simple_html_dom_node\parent().
    {
        $this->clear();
        // set the length of content before we do anything to it.
        $this->size = strlen($str);
        // Save the original size of the html that we got in. It might be useful to someone.
        $this->original_size = $this->size;
        //before we save the string as the doc... strip out the \r \n's if we are told to.
        if ($stripRN) {
            $str = str_replace("\r", " ", $str);
            $str = str_replace("\n", " ", $str);
            // set the length of content since we have changed it.
            $this->size = strlen($str);
        }
        $this->doc = $str;
        $this->pos = 0;
        $this->cursor = 1;
        $this->noise = array();
        $this->nodes = array();
        $this->lowercase = $lowercase;
        $this->default_br_text = $defaultBRText;
        $this->default_span_text = $defaultSpanText;
        $this->root = new simple_html_dom_node($this);
        $this->root->tag = 'root';
        $this->root->_[HDOM_INFO_BEGIN] = -1;
        $this->root->nodetype = HDOM_TYPE_ROOT;
        $this->parent = $this->root;
        if ($this->size>0) $this->char = $this->doc[0];
    }
read_tag()
read_tag () [protected]
Definition at line 1258 of file simple_html_dom.php.
References simple_html_dom_node\$parent, simple_html_dom_node\$tag, HDOM_INFO_BEGIN, HDOM_INFO_END, HDOM_INFO_ENDSPACE, HDOM_INFO_INNER, HDOM_INFO_QUOTE, HDOM_INFO_SPACE, HDOM_INFO_TEXT, HDOM_QUOTE_NO, HDOM_TYPE_COMMENT, HDOM_TYPE_ELEMENT, HDOM_TYPE_TEXT, HDOM_TYPE_UNKNOWN, and simple_html_dom_node\parent().
    {
        if ($this->char!=='<')
        {
            $this->root->_[HDOM_INFO_END] = $this->cursor;
            return false;
        }
        $begin_tag_pos = $this->pos;
        $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
        // end tag
        if ($this->char==='/')
        {
            $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
            // This represents the change in the simple_html_dom trunk from revision 180 to 181.
            // $this->skip($this->token_blank_t);
            $this->skip($this->token_blank);
            $tag = $this->copy_until_char('>');
            // skip attributes in end tag
            if (($pos = strpos($tag, ' '))!==false)
                $tag = substr($tag, 0, $pos);
            $parent_lower = strtolower($this->parent->tag);
            $tag_lower = strtolower($tag);
            if ($parent_lower!==$tag_lower)
            {
                if (isset($this->optional_closing_tags[$parent_lower]) && isset($this->block_tags[
      $tag_lower]))
                {
                    $this->parent->_[HDOM_INFO_END] = 0;
                    $org_parent = $this->parent;
                    while (($this->parent->parent) && strtolower($this->parent->tag)!==$tag_lower)
                        $this->parent = $this->parent->parent;
                    if (strtolower($this->parent->tag)!==$tag_lower) {
                        $this->parent = $org_parent; // restore origonal parent
                        if ($this->parent->parent) $this->parent = $this->parent->parent;
                        $this->parent->_[HDOM_INFO_END] =
      $this->cursor;
                        return $this->as_text_node($tag);
                    }
                }
                else if (($this->parent->parent) && isset($this->block_tags[$tag_lower]))
                {
                    $this->parent->_[HDOM_INFO_END] = 0;
                    $org_parent = $this->parent;
                    while (($this->parent->parent) && strtolower($this->parent->tag)!==$tag_lower)
                        $this->parent = $this->parent->parent;
                    if (strtolower($this->parent->tag)!==$tag_lower)
                    {
                        $this->parent = $org_parent; // restore origonal parent
                        $this->parent->_[HDOM_INFO_END] =
      $this->cursor;
                        return $this->as_text_node($tag);
                    }
                }
                else if (($this->parent->parent) && strtolower($this->parent->parent->tag)===$tag_lower)
                {
                    $this->parent->_[HDOM_INFO_END] = 0;
                    $this->parent = $this->parent->parent;
                }
                else
                    return $this->as_text_node($tag);
            }
            $this->parent->_[HDOM_INFO_END] = $this->cursor;
            if ($this->parent->parent) $this->parent = $this->parent->parent;
            $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
            return true;
        }
        $node = new simple_html_dom_node($this);
        $node->_[HDOM_INFO_BEGIN] = $this->cursor;
        ++$this->cursor;
        $tag = $this->copy_until($this->token_slash);
        $node->tag_start = $begin_tag_pos;
        // doctype, cdata & comments...
        if (isset($tag[0]) && $tag[0]==='!') {
            $node->_[HDOM_INFO_TEXT] = '<' . $tag . $this->
      copy_until_char('>');
            if (isset($tag[2]) && $tag[1]==='-' && $tag[2]==='-') {
                $node->nodetype = HDOM_TYPE_COMMENT;
                $node->tag = 'comment';
            } else {
                $node->nodetype = HDOM_TYPE_UNKNOWN;
                $node->tag = 'unknown';
            }
            if ($this->char==='>') $node->_[HDOM_INFO_TEXT].='>';
            $this->link_nodes($node, true);
            $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
            return true;
        }
        // text
        if ($pos=strpos($tag, '<')!==false) {
            $tag = '<' . substr($tag, 0, -1);
            $node->_[HDOM_INFO_TEXT] = $tag;
            $this->link_nodes($node, false);
            $this->char = $this->doc[--$this->pos]; // prev
            return true;
        }
        if (!preg_match("/^[\w-:]+$/", $tag)) {
            $node->_[HDOM_INFO_TEXT] = '<' . $tag . $this->
      copy_until('<>');
            if ($this->char==='<') {
                $this->link_nodes($node, false);
                return true;
            }
            if ($this->char==='>') $node->_[HDOM_INFO_TEXT].='>';
            $this->link_nodes($node, false);
            $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
            return true;
        }
        // begin tag
        $node->nodetype = HDOM_TYPE_ELEMENT;
        $tag_lower = strtolower($tag);
        $node->tag = ($this->lowercase) ? $tag_lower : $tag;
        // handle optional closing tags
        if (isset($this->optional_closing_tags[$tag_lower]))
        {
            while (isset($this->optional_closing_tags[$tag_lower][strtolower($this->parent->tag)]))
            {
                $this->parent->_[HDOM_INFO_END] = 0;
                $this->parent = $this->parent->parent;
            }
            $node->parent = $this->parent;
        }
        $guard = 0; // prevent infinity loop
        $space = array($this->copy_skip($this->token_blank), '', '');
        // attributes
        do
        {
            if ($this->char!==null && $space[0]==='')
            {
                break;
            }
            $name = $this->copy_until($this->token_equal);
            if ($guard===$this->pos)
            {
                $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; //
       next
                continue;
            }
            $guard = $this->pos;
            // handle endless '<'
            if ($this->pos>=$this->size-1 && $this->char!=='>') {
                $node->nodetype = HDOM_TYPE_TEXT;
                $node->_[HDOM_INFO_END] = 0;
                $node->_[HDOM_INFO_TEXT] = '<'.$tag . $space[0] . $name;
                $node->tag = 'text';
                $this->link_nodes($node, false);
                return true;
            }
            // handle mismatch '<'
            if ($this->doc[$this->pos-1]=='<') {
                $node->nodetype = HDOM_TYPE_TEXT;
                $node->tag = 'text';
                $node->attr = array();
                $node->_[HDOM_INFO_END] = 0;
                $node->_[HDOM_INFO_TEXT] = substr($this->doc, $begin_tag_pos, $this->pos-
      $begin_tag_pos-1);
                $this->pos -= 2;
                $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; //
       next
                $this->link_nodes($node, false);
                return true;
            }
            if ($name!=='/' && $name!=='') {
                $space[1] = $this->copy_skip($this->token_blank);
                $name = $this->restore_noise($name);
                if ($this->lowercase) $name = strtolower($name);
                if ($this->char==='=') {
                    $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; //
       next
                    $this->parse_attr($node, $name, $space);
                }
                else {
                    //no value attr: nowrap, checked selected...
                    $node->_[HDOM_INFO_QUOTE][] = HDOM_QUOTE_NO;
                    $node->attr[$name] = true;
                    if ($this->char!='>') $this->char = $this->doc[--$this->pos]; // prev
                }
                $node->_[HDOM_INFO_SPACE][] = $space;
                $space = array($this->copy_skip($this->token_blank), '', '');
            }
            else
                break;
        } while ($this->char!=='>' && $this->char!=='/');
        $this->link_nodes($node, true);
        $node->_[HDOM_INFO_ENDSPACE] = $space[0];
        // check self closing
        if ($this->copy_until_char_escape('>')==='/')
        {
            $node->_[HDOM_INFO_ENDSPACE] .= '/';
            $node->_[HDOM_INFO_END] = 0;
        }
        else
        {
            // reset parent
            if (!isset($this->self_closing_tags[strtolower($node->tag)])) $this->parent = $node;
        }
        $this->char = (++$this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
        // If it's a BR tag, we need to set it's text to the default text.
        // This way when we see it in plaintext, we can generate formatting that the user wants.
        // since a br tag never has sub nodes, this works well.
        if ($node->tag == "br")
        {
            $node->_[HDOM_INFO_INNER] = $this->default_br_text;
        }
        return true;
    }
remove_callback()
remove_callback ()
Definition at line 1096 of file simple_html_dom.php.
    {
        $this->callback = null;
    }
remove_noise()
remove_noise ($pattern, $remove_tag = false) [protected]
Definition at line 1615 of file simple_html_dom.php.
    {
        global $debugObject;
        if (is_object($debugObject)) { $debugObject->debugLogEntry(1); }
        $count = preg_match_all($pattern, $this->doc, $matches, PREG_SET_ORDER|PREG_OFFSET_CAPTURE);
        for ($i=$count-1; $i>-1; --$i)
        {
            $key = '___noise___'.sprintf('% 5d', count($this->noise)+1000);
            if (is_object($debugObject)) { $debugObject->debugLog(2, 'key is: ' . $key); }
            $idx = ($remove_tag) ? 0 : 1;
            $this->noise[$key] = $matches[$i][$idx][0];
            $this->doc = substr_replace($this->doc, $key, $matches[$i][$idx][1], strlen($matches[$i][$idx][
      0]));
        }
        // reset the length of content
        $this->size = strlen($this->doc);
        if ($this->size>0)
        {
            $this->char = $this->doc[0];
        }
    }
restore_noise()
restore_noise ($text)
Definition at line 1640 of file simple_html_dom.php.
    {
        global $debugObject;
        if (is_object($debugObject)) { $debugObject->debugLogEntry(1); }
        while (($pos=strpos($text, '___noise___'))!==false)
        {
            // Sometimes there is a broken piece of markup, and we don't GET the pos+11 etc... token which
       indicates a problem outside of us...
            if (strlen($text) > $pos+15)
            {
                $key = '___noise___'.$text[$pos+11].$text[$pos+12].$text[
      $pos+13].$text[$pos+14].$text[$pos+15];
                if (is_object($debugObject)) { $debugObject->debugLog(2, 'located key of: ' . $key); }
                if (isset($this->noise[$key]))
                {
                    $text = substr($text, 0, $pos).$this->noise[$key].substr($text,
      $pos+16);
                }
                else
                {
                    // do this to prevent an infinite loop.
                    $text = substr($text, 0, $pos).'UNDEFINED NOISE FOR KEY: '.$key . substr($text,
      $pos+16);
                }
            }
            else
            {
                // There is no valid key being given back to us... We must get rid of the ___noise___ or we
       will have a problem.
                $text = substr($text, 0, $pos).'NO NUMERIC NOISE KEY' . substr($text,
      $pos+11);
            }
        }
        return $text;
    }
save()
save ($filepath = '')
Definition at line 1102 of file simple_html_dom.php.
    {
        $ret = $this->root->innertext();
        if ($filepath!=='') file_put_contents($filepath, $ret, LOCK_EX);
        return $ret;
    }
search_noise()
search_noise ($text)
Definition at line 1673 of file simple_html_dom.php.
    {
        global $debugObject;
        if (is_object($debugObject)) { $debugObject->debugLogEntry(1); }
        foreach($this->noise as $noiseElement)
        {
            if (strpos($noiseElement, $text)!==false)
            {
                return $noiseElement;
            }
        }
    }
set_callback()
set_callback ($function_name)
Definition at line 1090 of file simple_html_dom.php.
    {
        $this->callback = $function_name;
    }
skip()
skip ($chars) [protected]
Definition at line 1541 of file simple_html_dom.php.
    {
        $this->pos += strspn($this->doc, $chars, $this->pos);
        $this->char = ($this->pos<$this->size) ? $this->doc[$this->pos] : null; // next
    }
Field Documentation
$_charset
$_charset = ''
Definition at line 991 of file simple_html_dom.php.
$_target_charset
$_target_charset = ''
Definition at line 992 of file simple_html_dom.php.
$block_tags
$block_tags = array('root'=>1, 'body'=>1, 'form'=>1, 'div'=>1, 'span'=>1, 'table'=>1) [protected]
Definition at line 998 of file simple_html_dom.php.
$callback
$callback = null
Definition at line 975 of file simple_html_dom.php.
$char
$char [protected]
Definition at line 982 of file simple_html_dom.php.
$cursor
$cursor [protected]
Definition at line 983 of file simple_html_dom.php.
$default_br_text
$default_br_text = `` [protected]
Definition at line 993 of file simple_html_dom.php.
$default_span_text
$default_span_text = ``
Definition at line 994 of file simple_html_dom.php.
$doc
$doc [protected]
Definition at line 981 of file simple_html_dom.php.
$lowercase
$lowercase = false
Definition at line 976 of file simple_html_dom.php.
$nodes
$nodes = array()
Definition at line 974 of file simple_html_dom.php.
$noise
$noise = array() [protected]
Definition at line 985 of file simple_html_dom.php.
$optional_closing_tags
$optional_closing_tags [protected]
Initial value:
= array(
        'tr'=>array('tr'=>1, 'td'=>1, 'th'=>1),
        'th'=>array('th'=>1),
        'td'=>array('td'=>1),
        'li'=>array('li'=>1),
        'dt'=>array('dt'=>1, 'dd'=>1),
        'dd'=>array('dd'=>1, 'dt'=>1),
        'dl'=>array('dd'=>1, 'dt'=>1),
        'p'=>array('p'=>1),
        'nobr'=>array('nobr'=>1),
        'b'=>array('b'=>1),
        'option'=>array('option'=>1),
    )
Definition at line 1001 of file simple_html_dom.php.
$original_size
$original_size
Definition at line 978 of file simple_html_dom.php.
$parent
$parent [protected]
Definition at line 984 of file simple_html_dom.php.
$pos
$pos [protected]
Definition at line 980 of file simple_html_dom.php.
$root
$root = null
Definition at line 973 of file simple_html_dom.php.
$self_closing_tags
$self_closing_tags = array('img'=>1, 'br'=>1, 'input'=>1, 'meta'=>1, 'link'=>1, 'hr'=>1, 'base'=>1, 'embed'=>1, 'spacer'=>1) [protected]
Definition at line 997 of file simple_html_dom.php.
$size
$size
Definition at line 979 of file simple_html_dom.php.
$token_attr
$token_attr = ' >' [protected]
Definition at line 989 of file simple_html_dom.php.
$token_blank
$token_blank = ` \t\r\n` [protected]
Definition at line 986 of file simple_html_dom.php.
$token_equal
$token_equal = ' =/>' [protected]
Definition at line 987 of file simple_html_dom.php.
$token_slash
$token_slash = ` />\r\n\t` [protected]
Definition at line 988 of file simple_html_dom.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/libraries/simple_html_dom.php