Session Class Reference
Static Public Member Functions
static init ()
static set ($key, $value)
static get ($key)
static destroy ($key)
Detailed Description
Definition at line 2 of file Session.php.
Member Function Documentation
destroy()
static destroy ($key) [static]
Destroys session
Definition at line 31 of file Session.php.
Referenced by Auth\logout().
                                         {
        if (isset($_SESSION[$key])) {
            unset($_SESSION[$key]);
            session_destroy();
        }
    }
get()
static get ($key) [static]
Gets session value
Returns
string array
Definition at line 22 of file Session.php.
Referenced by Auth\user().
                                     {
        if (isset($_SESSION[$key])) {
            return $_SESSION[$key];
        }
    }
init()
static init () [static]
Initializes session
Definition at line 6 of file Session.php.
Referenced by Auth\login(), Auth\logout(), and Auth\user().
                                  {
        session_start();
    }
set()
static set ($key, $value) [static]
Sets session value
Definition at line 13 of file Session.php.
Referenced by Auth\login().
                                             {
        $_SESSION[$key] = $value;
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/libraries/Session.php