Redirect Class Reference
Static Public Member Functions
static url ($url)
static controller ($controller)
Detailed Description
Definition at line 2 of file Redirect.php.
Member Function Documentation
controller()
static controller ($controller) [static]
Redirects to given controller and method
Parameters
string $controller
Definition at line 18 of file Redirect.php.
Referenced by Prices\bedreBegravelse(), Login\createUser(), Administration\createUser(), Administration\deleteUser(), Prices\dkBegravelse(), Administration\editUser(), Administration\editUserPost(), Login\forgottenPassword(), Administration\index(), Home\index(), Contact\index(), Login\loginPost(), Login\logout(), Basic\redirectToController(), Contact\sendMail(), Home\sendTwoFactor(), Administration\user(), and Home\verifyTwoFactor().
                                                   {
        $atSign = explode('@', $controller);
        if (strpos($controller, '@') !== false) {
            header('Location:' . dirname($_SERVER['PHP_SELF']) . '/' . $atSign[0] . '/' . $atSign[1]);
        }
        else {
            header('Location:'. dirname($_SERVER['PHP_SELF']) . '/' . $atSign[0]);
        }
        exit();
    }
url()
static url ($url) [static]
Redirects to given URL
Parameters
string $url
Definition at line 8 of file Redirect.php.
Referenced by Basic\redirectToUrl().
                                     {
        header('Location: ' . $url);
        exit();
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/libraries/Redirect.php