Contact Class Reference
Public Member Functions
index ()
sendMail ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file Contact.php.
Member Function Documentation
index()
index ()
Definition at line 5 of file Contact.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\renderView(), and Auth\user().
                            {
        $user = $this->loadModel('Users');
        $user = Auth::user();
        if ($user) {
            echo $this->renderView('layout/contact');
        }
        else {
            Redirect::controller('Login@index');
        }
    }
sendMail()
sendMail ()
Definition at line 16 of file Contact.php.
References Redirect\controller(), MAILGUN_DOMAIN, MAILGUN_KEY, and BaseController\postInput().
                               {
        $client = new Mailgun(MAILGUN_KEY);
        $domain = MAILGUN_DOMAIN;
        $client->sendMessage($domain,
            array('from' => 'Mailgun Sandbox
       <postmaster@sandbox5c2500d99acf4cbfa26fa88a596a49bd.mailgun.org>',
                'to' => 'danielwinther@hotmail.dk',
                'subject' => $this->postInput('subject'),
                'text' => $this->postInput('message')));
        Redirect::controller('Contact@index');
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/controllers/Contact.php