Login Class Reference
Public Member Functions
index ()
loginPost ()
logout ()
createUser ()
forgottenPassword ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file Login.php.
Member Function Documentation
createUser()
createUser ()
Definition at line 27 of file Login.php.
References Redirect\controller(), Hash\create(), BaseController\loadModel(), and BaseController\postInput().
                                 {
        $user = $this->loadModel('Users');
        $this->loadModel('Roles');
        if (!Users::where('userName', $this->postInput('userName'))->first()) {
            $user->userName = $this->postInput('userName');
            $user->password = Hash::create($this->postInput('password'),
      PASSWORD_BCRYPT);
            $user->firstName = $this->postInput('firstName');
            $user->lastName = $this->postInput('lastName');
            $user->age = $this->postInput('age');
            $user->avatar = $this->postInput('avatar');
            $user->email = $this->postInput('email');
            $user->phone = $this->postInput('phone');
            $user->roleId = 1;
            $user->save();
        }
        Redirect::controller('Login@index');
    }
forgottenPassword()
forgottenPassword ()
Definition at line 47 of file Login.php.
References Redirect\controller(), Hash\create(), Auth\generateCode(), BaseController\loadModel(), MAILGUN_DOMAIN, MAILGUN_KEY, and BaseController\postInput().
                                        {
        $user = $this->loadModel('Users');
        $user = Users::where('userName', $this->postInput('userName'))->first();
        if ($user) {
            $password = Auth::generateCode(10);
            $user->password = Hash::create($password, PASSWORD_BCRYPT);
            $client = new Mailgun(MAILGUN_KEY);
            $domain = MAILGUN_DOMAIN;
            $client->sendMessage($domain,
                array('from' => 'Mailgun Sandbox
       <postmaster@sandbox5c2500d99acf4cbfa26fa88a596a49bd.mailgun.org>',
                    'to' => $user->email,
                    'subject' => 'MVC Framework - new password',
                    'text' => 'Your new password is: ' . $password));
            $user->save();
            Redirect::controller('Login@index');
        }
        else {
            Redirect::controller('Login@index');
        }
    }
index()
index ()
Definition at line 5 of file Login.php.
References BaseController\renderView().
                            {
        echo $this->renderView('layout/login');
    }
loginPost()
loginPost ()
Definition at line 8 of file Login.php.
References Redirect\controller(), BaseController\loadModel(), Auth\login(), BaseController\postInput(), and Auth\user().
                                {
        $user = $this->loadModel('Users');
        Auth::login($this->postInput('userName'), $this->
      postInput('password'));
        $user = Auth::user();
        if ($user) {
            Redirect::controller('Home@index');
        }
        else {
            Auth::login();
            Redirect::controller('Login@index');
        }
    }
logout()
logout ()
Definition at line 22 of file Login.php.
References Redirect\controller(), and Auth\logout().
                             {
        Auth::logout();
        Redirect::controller('Login@index');
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/controllers/Login.php