Prices Class Reference
Public Member Functions
bedreBegravelse ()
dkBegravelse ()
Additional Inherited Members
Detailed Description
Definition at line 2 of file Prices.php.
Member Function Documentation
bedreBegravelse()
bedreBegravelse ()
Definition at line 3 of file Prices.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\renderView(), BaseController\scrape(), and Auth\user().
                                      {
        $user = $this->loadModel('Users');
        $user = Auth::user();
        if ($user) {
            $html = $this->scrape('GET', '
      https://www.bedrebegravelse.dk/424/bedemand-priser-paa-begravelse-eller-bisaettelse');
            $html = $html->find('#divPreview > .fourth');
            echo $this->renderView('layout/bedre_begravelse', ['html' => $html]);
        }
        else {
            Redirect::controller('Login@index');
        }
    }
dkBegravelse()
dkBegravelse ()
Definition at line 17 of file Prices.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\renderView(), BaseController\scrape(), and Auth\user().
                                   {
        $user = $this->loadModel('Users');
        $user = Auth::user();
        if ($user) {
            $html = $this->scrape('GET', 'http://www.dk-begravelse.dk/Priser/Kister');
            $html = $html->find('#eid507114 table td table');
            echo $this->renderView('layout/dk_begravelse', ['html' => $html]);
        }
        else {
            Redirect::controller('Login@index');
        }
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/controllers/Prices.php