Hash Class Reference
Static Public Member Functions
static create ($password, $algorithm, $salt)
static verify ($password, $algorithm)
Detailed Description
Definition at line 2 of file Hash.php.
Member Function Documentation
create()
static create ($password, $algorithm, $salt) [static]
Creates a hashed string
Parameters
string $password
string $algorithm
Returns
string
Definition at line 10 of file Hash.php.
Referenced by Basic\editUserPost(), Basic\returnHash(), and verify().
                                                                {
        return password_hash($password, $algorithm, array('cost' => 10, 'salt' => $salt));
    }
verify()
static verify ($password, $algorithm) [static]
Verify a hashed string
Parameters
string $password
string $algorithm
Returns
string $hash
Definition at line 21 of file Hash.php.
References create(), and SALT.
Referenced by Auth\login().
                                                         {
        $hash = Hash::create($password, PASSWORD_BCRYPT, SALT);
        if (password_verify($password, $hash)) {
            return $hash;
        }
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/libraries/Hash.php