BaseController Class Reference
Protected Member Functions
loadModel ($model, $constructor=[])
postInput ($input=null)
renderView ($view, $data=[])
redirectUrl ($url)
redirectController ($controller)
scrape ($action, $url, $curl=null)
session ($url, $postData)
hashString ($string)
Detailed Description
Definition at line 3 of file BaseController.php.
Member Function Documentation
hashString()
hashString ($string) [protected]
Hashes a given string and adds a salt to it
Parameters
string $string
Returns
string
Definition at line 161 of file BaseController.php.
References initializeConfig().
Referenced by Basic\returnHash().
                                           {
        $config = initializeConfig();
        return md5($string + $config['salt']);
    }
loadModel()
loadModel ($model, $constructor = []) [protected]
Loads a given model into the controller
Parameters
string $model
array $constructor
Returns
object $model
Definition at line 11 of file BaseController.php.
Referenced by Basic\createUser(), Basic\deleteUser(), Basic\editUser(), Basic\editUserPost(), Basic\index(), Basic\returnModel(), and Basic\user().
                                                            {
        if (file_exists(realpath(__DIR__ . '/..') . '/models/' . $model . '.php')) {
            require_once realpath(__DIR__ . '/..') . '/models/' . $model . '.php';
        }
        else {
            throw new ModelNotFound('ModelNotFound', 'Model "' . $model . '" not found.');
            exit();
        }
        return new $model($constructor);
    }
postInput()
postInput ($input = null) [protected]
Sanitizes and returns POST data
Parameters
string $input
Returns
string/array
Definition at line 29 of file BaseController.php.
Referenced by Basic\createUser(), and Basic\editUserPost().
                                                {
        $post = filter_input_array(INPUT_POST, FILTER_SANITIZE_STRING);
        if ($input) {
            return $post[$input];
        }
        else {
            return $post;
        }
    }
redirectController()
redirectController ($controller) [protected]
Redirects to given controller and method
Parameters
string $controller
Definition at line 73 of file BaseController.php.
References initializeConfig().
Referenced by Basic\createUser(), Basic\deleteUser(), Basic\editUserPost(), and Basic\redirectToController().
                                                       {
        $atSign = explode('@', $controller);
        if (strpos($controller, '@') !== false) {
            header('Location:' . dirname($_SERVER['PHP_SELF']) . '/' . $atSign[0] . '/' . $atSign[1]);
        }
        else {
            $config = initializeConfig();
            header('Location:'. dirname($_SERVER['PHP_SELF']) . '/' . $atSign[0]);
        }
        exit();
    }
redirectUrl()
redirectUrl ($url) [protected]
Redirects to given URL
Parameters
string $url
Definition at line 63 of file BaseController.php.
Referenced by Basic\redirectToUrl().
                                         {
        header('Location: ' . $url);
        exit();
    }
renderView()
renderView ($view, $data = []) [protected]
Loads a given view into the controller
Parameters
string $view
array $data
Definition at line 46 of file BaseController.php.
Referenced by Basic\editUser(), Basic\index(), and Basic\user().
                                                     {
        $loader = new Twig_Loader_Filesystem(realpath(__DIR__ . '/..') . '/views');
        $twig = new Twig_Environment($loader, [
            'debug' => true,
            ]);
        $twig->addExtension(new Twig_Extension_Debug());
        return $twig->render($view . '.php', [
            'data' => $data
            ]);
    }
scrape()
scrape ($action, $url, $curl = null) [protected]
Scrapes HTML source code from the given URL
Parameters
string $url
string $action
curl $curl
Returns
string $html
Definition at line 94 of file BaseController.php.
References str_get_html().
Referenced by Basic\scrapePdf(), and Basic\scrapeWebsite().
                                                           {
        $html = new simple_html_dom();
        switch (strtoupper($action)) {
            case 'GET':
            if ($curl) {
                curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($curl, CURLOPT_POST, 0);
                curl_setopt($curl, CURLOPT_URL, $url);
                $html = str_get_html(curl_exec($curl));
                curl_close($curl);
            }
            else {
                $html->load_file($url);
            }
            break;
            
            case 'PDF':
            $parser = new Parser();
            $pdf = $parser->parseFile($url);
            return $pdf;
            break;
            
        }
        return $html;
    }
session()
session ($url, $postData) [protected]
Initializes session with cURL and saves session cookies in file for later retrieval
Parameters
string $url
array $postData
Returns
$curl
Definition at line 130 of file BaseController.php.
                                                {
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_URL, $url);
        $cookie = dirname(__FILE__) . '/cookies.txt';
        $timeout = 30;
        curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36
       (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36');
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($curl, CURLOPT_TIMEOUT, 10);
        curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, $timeout);
        curl_setopt($curl, CURLOPT_COOKIEJAR, $cookie);
        curl_setopt($curl, CURLOPT_COOKIEFILE, $cookie);
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($postData));
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
        unlink($cookie);
        curl_exec($curl);
        return $curl;
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/kernel/BaseController.php