Administration Class Reference
Public Member Functions
index ()
user ($id='')
createUser ()
editUser ($id='')
editUserPost ()
deleteUser ($id='')
Additional Inherited Members
Detailed Description
Definition at line 2 of file Administration.php.
Member Function Documentation
createUser()
createUser ()
Definition at line 30 of file Administration.php.
References Redirect\controller(), Hash\create(), BaseController\loadModel(), and BaseController\postInput().
                                 {
        $user = $this->loadModel('Users');
        $this->loadModel('Roles');
        if (!Users::where('userName', $this->postInput('userName'))->first()) {
            $user->userName = $this->postInput('userName');
            $user->password = Hash::create($this->postInput('password'),
      PASSWORD_BCRYPT);
            $user->firstName = $this->postInput('firstName');
            $user->lastName = $this->postInput('lastName');
            $user->age = $this->postInput('age');
            $user->avatar = $this->postInput('avatar');
            $user->email = $this->postInput('email');
            $user->phone = $this->postInput('phone');
            $user->roleId = $this->postInput('role');
            $user->save();
        }
        Redirect::controller('Administration@index');
    }
deleteUser()
deleteUser ($id = '')
Definition at line 80 of file Administration.php.
References Redirect\controller(), and BaseController\loadModel().
                                         {
        $user = $this->loadModel('Users');
        if ($user) {
            $user = Users::find($id);
            $user->delete();
            Redirect::controller('Administration/index');
        }
        else {
            Redirect::controller('Login@index');
        }
    }
editUser()
editUser ($id = '')
Definition at line 49 of file Administration.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\renderView(), and Auth\user().
                                       {
        $user = $this->loadModel('Users');
        $roles = $this->loadModel('Roles');
        $user = Auth::user();
        if ($user) {
            $user = Users::find($id);
            $roles = Roles::all();
            echo $this->renderView('layout/administration_edit', ['user' => $user, 'roles' =>
      $roles]);
        }
        else {
            Redirect::controller('Login@index');
        }
    }
editUserPost()
editUserPost ()
Definition at line 63 of file Administration.php.
References Redirect\controller(), Hash\create(), BaseController\loadModel(), and BaseController\postInput().
                                   {
        $user = $this->loadModel('Users');
        $this->loadModel('Roles');
        $user = Users::find($this->postInput('id'));
        $user->password = Hash::create($this->postInput('password'), PASSWORD_BCRYPT);
        $user->firstName = $this->postInput('firstName');
        $user->lastName = $this->postInput('lastName');
        $user->age = $this->postInput('age');
        $user->avatar = $this->postInput('avatar');
        $user->email = $this->postInput('email');
        $user->phone = $this->postInput('phone');
        $user->roleId = $this->postInput('role');
        $user->save();
        Redirect::controller('Administration@index');
    }
index()
index ()
Definition at line 3 of file Administration.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\renderView(), and Auth\user().
                            {
        $users = $this->loadModel('Users');
        $roles = $this->loadModel('Roles');
        $user = Auth::user();
        if ($user) {
            $users = Users::all()->sortBy('firstName');
            $roles = Roles::all();
            echo $this->renderView('layout/administration', ['userArray' => $users, 'user' =>
      $user, 'roles' => $roles]);
        }
        else {
            Redirect::controller('Login@index');
        }
    }
user()
user ($id = '')
Definition at line 17 of file Administration.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\renderView(), and Auth\user().
                                   {
        $user = $this->loadModel('Users');
        $this->loadModel('Roles');
        $user = Auth::user();
        if ($user) {
            $user = Users::find($id);
            echo $this->renderView('layout/administration_detail', ['user' => $user]);
        }
        else {
            Redirect::controller('Login@index');
        }
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/controllers/Administration.php