Home Class Reference
Public Member Functions
index ()
sendTwoFactor ()
verifyTwoFactor ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file Home.php.
Member Function Documentation
index()
index ()
Definition at line 5 of file Home.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\renderView(), and Auth\user().
                            {
        $user = $this->loadModel('Users');
        $this->loadModel('Roles');
        $user = Auth::user();
        if ($user) {
            echo $this->renderView('layout/home', ['user' => $user]);
        }
        else {
            Redirect::controller('Login@index');
        }
    }
sendTwoFactor()
sendTwoFactor ()
Definition at line 17 of file Home.php.
References Redirect\controller(), BaseController\loadModel(), and Auth\sendTwoFactor().
                                    {
        $user = $this->loadModel('Users');
        Auth::sendTwoFactor();
        Redirect::controller('Home@index');
    }
verifyTwoFactor()
verifyTwoFactor ()
Definition at line 23 of file Home.php.
References Redirect\controller(), BaseController\loadModel(), BaseController\postInput(), and Auth\verifyTwoFactor().
                                      {
        $user = $this->loadModel('Users');
        Auth::verifyTwoFactor($this->postInput('code'));
        Redirect::controller('Home@index');
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/controllers/Home.php