Auth Class Reference
Static Public Member Functions
static login ($userName, $password)
static logout ()
static user ()
static sendTwoFactor ()
static generateCode ($length=4)
static verifyTwoFactor ($code)
Detailed Description
Definition at line 4 of file Auth.php.
Member Function Documentation
generateCode()
static generateCode ($length = 4) [static]
Generate Two-factor code
Returns
string
Definition at line 65 of file Auth.php.
Referenced by Login\forgottenPassword(), and sendTwoFactor().
                                                     {
        return substr(str_shuffle(str_repeat($code = '
      0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil($length / strlen($code)))), 1, $length);
    }
login()
static login ($userName, $password) [static]
Logins to user account
Parameters
string $userName
string $password
Definition at line 11 of file Auth.php.
References Session\init(), Session\set(), and Hash\verify().
Referenced by Login\loginPost().
                                                       {
        $user = Users::where('userName', $userName)->where('password',
      Hash::verify($password, PASSWORD_BCRYPT))->first();
        if ($user) {
            Session::init();
            Session::set('id', $user->id);
        }
    }
logout()
static logout () [static]
Logouts out of user account
Definition at line 23 of file Auth.php.
References Session\destroy(), and Session\init().
Referenced by Login\logout().
                                    {
        Session::init();
        Session::destroy('id');
    }
sendTwoFactor()
static sendTwoFactor () [static]
Sends two-factor code via SMS
Definition at line 43 of file Auth.php.
References generateCode(), TWILIO_SID, TWILIO_TOKEN, and user().
Referenced by Home\sendTwoFactor().
                                           {
        $user = Auth::user();
        $code = Auth::generateCode();
        $client = new Client(TWILIO_SID, TWILIO_TOKEN);
        $client->messages->create(
            $user->phone,
            [
            'from' => '+46769447755',
            'body' => 'Two-factor code: ' . $code
            ]
            );
        $user->twoFactorCode = $code;
        $user->save();
    }
user()
static user () [static]
Gets user data from session
Returns
Users
Definition at line 33 of file Auth.php.
References Session\get(), and Session\init().
Referenced by Prices\bedreBegravelse(), Prices\dkBegravelse(), Administration\editUser(), Api\index(), Administration\index(), Contact\index(), Home\index(), Login\loginPost(), sendTwoFactor(), Administration\user(), and verifyTwoFactor().
                                  {
        Session::init();
        $user = Session::get('id');
        
        return Users::find($user);
    }
verifyTwoFactor()
static verifyTwoFactor ($code) [static]
Verifies two-factor code
Definition at line 72 of file Auth.php.
References user().
Referenced by Home\verifyTwoFactor().
                                                  {
        $user = Auth::user();
        if ($user->twoFactorCode == $code) {
            $user->isTwoFactor = true;
        }
        else {
            $user->isTwoFactor = false;
        }
        $user->save();
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/libraries/Auth.php