Basic Class Reference
Public Member Functions
index ()
user ($id='')
scrapeWebsite ()
scrapePdf ()
returnModel ()
returnHash ()
createUser ()
editUser ($id='')
editUserPost ()
deleteUser ($id='')
sendMail ()
sendSMS ()
returnString ()
returnInt ()
redirectToUrl ()
redirectToController ()
returnParameter ($parameter='')
returnTwoParameters ($parameter1='', $parameter2='')
Additional Inherited Members
Detailed Description
Definition at line 5 of file Basic.php.
Member Function Documentation
createUser()
createUser ()
Definition at line 45 of file Basic.php.
References BaseController\loadModel(), BaseController\postInput(), and BaseController\redirectController().
                                 {
        $postInput = $this->postInput();
        $user = $this->loadModel('Users');
        Users::create($postInput);
        $this->redirectController('Basic');
    }
deleteUser()
deleteUser ($id = '')
Definition at line 73 of file Basic.php.
References BaseController\loadModel(), and BaseController\redirectController().
                                         {
        $user = $this->loadModel('Users');
        $user = Users::find($id);
        $user->delete();
        $this->redirectController('Basic');
    }
editUser()
editUser ($id = '')
Definition at line 53 of file Basic.php.
References BaseController\loadModel(), and BaseController\renderView().
                                       {
        $user = $this->loadModel('Users');
        $user = Users::find($id);
        echo $this->renderView('layout/basic_edit', ['user' => $user]);
    }
editUserPost()
editUserPost ()
Definition at line 59 of file Basic.php.
References BaseController\loadModel(), BaseController\postInput(), and BaseController\redirectController().
                                   {
        $user = $this->loadModel('Users');
        $user = Users::find($this->postInput('id'));
        $user->firstName = $this->postInput('firstName');
        $user->lastName = $this->postInput('lastName');
        $user->age = $this->postInput('age');
        $user->avatar = $this->postInput('avatar');
        $user->email = $this->postInput('email');
        $user->phone = $this->postInput('phone');
        $user->save();
        $this->redirectController('Basic');
    }
index()
index ()
Definition at line 6 of file Basic.php.
References BaseController\loadModel(), and BaseController\renderView().
                            {
        $users = $this->loadModel('Users');
        $users = Users::all()->sortBy('firstName');
        echo $this->renderView('layout/basic', ['userArray' => $users]);
    }
redirectToController()
redirectToController ()
Definition at line 115 of file Basic.php.
References BaseController\redirectController().
                                           {
        $this->redirectController('Basic');
    }
redirectToUrl()
redirectToUrl ()
Definition at line 112 of file Basic.php.
References BaseController\redirectUrl().
                                    {
        $this->redirectUrl(__DIR__ . '/returnString');
    }
returnHash()
returnHash ()
Definition at line 42 of file Basic.php.
References BaseController\hashString().
                                 {
        return $this->hashString('daniel');
    }
returnInt()
returnInt ()
Definition at line 109 of file Basic.php.
                                {
        return 24;
    }
returnModel()
returnModel ()
Definition at line 36 of file Basic.php.
References BaseController\loadModel().
                                  {
        $user = $this->loadModel('User');
        $user->setFirstName('daniel');
        return $user;
    }
returnParameter()
returnParameter ($parameter = '')
Definition at line 118 of file Basic.php.
                                                     {
        return $parameter;
    }
returnString()
returnString ()
Definition at line 106 of file Basic.php.
                                   {
        return 'daniel';
    }
returnTwoParameters()
returnTwoParameters ($parameter1 = '', $parameter2 = '')
Definition at line 121 of file Basic.php.
                                                                            {
        return $parameter1 . $parameter2;
    }
scrapePdf()
scrapePdf ()
Definition at line 26 of file Basic.php.
References BaseController\scrape().
                                {
        $pdf = $this->scrape('PDF', '
      http://www.begravelsedanmark.dk/wp-content/uploads/2015/10/BDK-butik-prisliste-2015.pdf');
        $text = $pdf->getText();
        $text = preg_replace('/[\n\r]/', '<br>', $text);
        $string = '2015';
        $t = explode($string, $text);
        return $t[0] . $string;
    }
scrapeWebsite()
scrapeWebsite ()
Definition at line 18 of file Basic.php.
References BaseController\scrape().
                                    {
        /*$curl = $this->session('https://m.facebook.com/login.php', ['email' => '', 'pass' => '',
       '_fb_noscript' => 'true']);
        $html = $this->scrape('GET', 'https://m.facebook.com/danielwintherjensendk/friends/', $curl);*/
        $html = $this->scrape('GET', 'http://ekstrabladet.dk/');
        return $html->getElementByTagName('title')->plaintext;
    }
sendMail()
sendMail ()
Definition at line 80 of file Basic.php.
References initializeConfig().
                               {
        $config = initializeConfig();
        $mgClient = new Mailgun($config['mailgunKey']);
        $domain = $config['mailgunDomain'];
        $result = $mgClient->sendMessage($domain,
            array('from' => 'Mailgun Sandbox
       <postmaster@sandbox5c2500d99acf4cbfa26fa88a596a49bd.mailgun.org>',
                'to' => 'Daniel Winther Jensen <danielwinther@hotmail.dk>',
                'subject' => 'Hello Daniel Winther Jensen',
                'text' => 'Congratulations Daniel Winther Jensen, you just sent an email with Mailgun!
       You are truly awesome! You can see a record of this email in your logs: https://mailgun.com/cp/log . You
       can send up to 300 emails/day from this sandbox server. Next, you should add your own domain so you can send
       10,000 emails/month for free.'));
    }
sendSMS()
sendSMS ()
Definition at line 91 of file Basic.php.
References initializeConfig().
                              {
        $config = initializeConfig();
        $sid = $config['twilioSid'];
        $token = $config['twilioToken'];
        $client = new Client($sid, $token);
        $client->messages->create(
            '+4542341338',
            array(
                'from' => '+46769447755',
                'body' => 'This is a test'
                )
            );
    }
user()
user ($id = '')
Definition at line 12 of file Basic.php.
References BaseController\loadModel(), and BaseController\renderView().
                                   {
        $user = $this->loadModel('Users');
        $user = Users::find($id);
        echo $this->renderView('layout/basic_detail', ['user' => $user]);
    }
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/controllers/Basic.php