Application Class Reference
Public Member Functions
__construct ()
Protected Member Functions
parseUrl ()
load ($url)
Protected Attributes
$controller = 'Basic'
$method = 'index'
$parameters = []
Detailed Description
Definition at line 2 of file Application.php.
Constructor & Destructor Documentation
__construct()
Application::__construct ()
Initializes the application
Definition at line 19 of file Application.php.
References load(), and parseUrl().
                                  {
        $this->load($this->parseUrl());
    }
Member Function Documentation
load()
Application::load ($url) [protected]
Loads a given controller, method and parameter based on the URL
Parameters
string $url
Definition at line 39 of file Application.php.
References $controller.
Referenced by __construct().
                                  {
        if (isset($url[0])) {
            if (file_exists(realpath(__DIR__ . '/..') . '/controllers/' . $url[0] . '.php')) {
                $this->controller = $url[0];
                unset($url[0]);
            }
            else {
                $this->controller = $url[0];
                throw new ControllerNotFound('ControllerNotFound', 'Controller "' .
      $this->controller . '" not found.');
                exit();
            }
        }
        
        require_once realpath(__DIR__ . '/..') . '/controllers/' . $this->controller . '.php';
        $this->controller = new $this->controller;
        if (isset($url[1])) {
            if (method_exists($this->controller, $url[1])) {
                $this->method = $url[1];
                unset($url[1]);
            }
            else {
                $this->method = $url[1];
                throw new MethodNotFound('MethodNotFound', 'Method "' . $this->method . '"
       not found.');
                exit();
            }
        }
        $this->parameters = $url ? array_values($url) : [];
        call_user_func_array([$this->controller, $this->method], $this->parameters);
    }
parseUrl()
Application::parseUrl () [protected]
Parses a given URL to make it read controllers, methods and parameters properly
Returns
string
Definition at line 28 of file Application.php.
Referenced by __construct().
                                  {
        if (isset($_GET['url'])) {
            return explode('/', filter_var(rtrim($_GET['url'], '/'), FILTER_SANITIZE_URL));
        }
    }
Member Data Documentation
$controller
string Application::$controller = 'Basic' [protected]
Definition at line 6 of file Application.php.
Referenced by load().
$method
Application::$method = 'index' [protected]
Definition at line 10 of file Application.php.
$parameters
Application::$parameters = [] [protected]
Definition at line 14 of file Application.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/kernal/Application.php