simple_html_dom_node Class Reference
Public Member Functions
__construct ($dom)
__destruct ()
__toString ()
clear ()
dump ($show_attr=true, $deep=0)
dump_node ($echo=true)
parent ($parent=null)
has_child ()
children ($idx=-1)
first_child ()
last_child ()
next_sibling ()
prev_sibling ()
find_ancestor_tag ($tag)
innertext ()
outertext ()
text ()
xmltext ()
makeup ()
find ($selector, $idx=null, $lowercase=false)
__get ($name)
__set ($name, $value)
__isset ($name)
__unset ($name)
convert_text ($text)
get_display_size ()
getAllAttributes ()
getAttribute ($name)
setAttribute ($name, $value)
hasAttribute ($name)
removeAttribute ($name)
getElementById ($id)
getElementsById ($id, $idx=null)
getElementByTagName ($name)
getElementsByTagName ($name, $idx=null)
parentNode ()
childNodes ($idx=-1)
firstChild ()
lastChild ()
nextSibling ()
previousSibling ()
hasChildNodes ()
nodeName ()
appendChild ($node)
Static Public Member Functions
static is_utf8 ($str)
Data Fields
$nodetype = HDOM_TYPE_TEXT
$tag = 'text'
$attr = array()
$children = array()
$nodes = array()
$parent = null
$_ = array()
$tag_start = 0
Protected Member Functions
seek ($selector, &$ret, $lowercase=false)
match ($exp, $pattern, $value)
parse_selector ($selector_string)
Detailed Description
Definition at line 114 of file simple_html_dom.php.
Constructor & Destructor Documentation
__construct ($dom)
Definition at line 127 of file simple_html_dom.php.
    {
        $this->dom = $dom;
        $dom->nodes[] = $this;
    }
__destruct ()
Definition at line 133 of file simple_html_dom.php.
References clear().
    {
        $this->clear();
    }
Member Function Documentation
__get ($name)
Definition at line 720 of file simple_html_dom.php.
References convert_text(), innertext(), outertext(), text(), and xmltext().
Referenced by getAttribute().
                          {
        if (isset($this->attr[$name]))
        {
            return $this->convert_text($this->attr[$name]);
        }
        switch ($name) {
            case 'outertext': return $this->outertext();
            case 'innertext': return $this->innertext();
            case 'plaintext': return $this->text();
            case 'xmltext': return $this->xmltext();
            default: return array_key_exists($name, $this->attr);
        }
    }
__isset ($name)
Definition at line 748 of file simple_html_dom.php.
Referenced by hasAttribute().
                            {
        switch ($name) {
            case 'outertext': return true;
            case 'innertext': return true;
            case 'plaintext': return true;
        }
        //no value attr: nowrap, checked selected...
        return (array_key_exists($name, $this->attr)) ? true : isset($this->attr[$name]);
    }
__set ($name, $value)
Definition at line 734 of file simple_html_dom.php.
References HDOM_INFO_INNER, HDOM_INFO_OUTER, HDOM_INFO_QUOTE, HDOM_INFO_SPACE, HDOM_INFO_TEXT, and HDOM_QUOTE_DOUBLE.
Referenced by removeAttribute(), and setAttribute().
                                  {
        switch ($name) {
            case 'outertext': return $this->_[HDOM_INFO_OUTER] = $value;
            case 'innertext':
                if (isset($this->_[HDOM_INFO_TEXT])) return $this->_[
      HDOM_INFO_TEXT] = $value;
                return $this->_[HDOM_INFO_INNER] = $value;
        }
        if (!isset($this->attr[$name])) {
            $this->_[HDOM_INFO_SPACE][] = array(' ', '', '');
            $this->_[HDOM_INFO_QUOTE][] = HDOM_QUOTE_DOUBLE;
        }
        $this->attr[$name] = $value;
    }
__toString ()
Definition at line 138 of file simple_html_dom.php.
References outertext().
    {
        return $this->outertext();
    }
__unset ($name)
Definition at line 758 of file simple_html_dom.php.
                            {
        if (isset($this->attr[$name]))
            unset($this->attr[$name]);
    }
appendChild ($node)
Definition at line 959 of file simple_html_dom.php.
{$node->parent($this); return $node;}
childNodes ($idx = -1)
Definition at line 952 of file simple_html_dom.php.
References children().
{return $this->children($idx);}
children ($idx = -1)
Definition at line 265 of file simple_html_dom.php.
References $children.
Referenced by childNodes(), clear(), dump_node(), first_child(), has_child(), last_child(), and seek().
    {
        if ($idx===-1)
        {
            return $this->children;
        }
        if (isset($this->children[$idx])) return $this->children[$idx];
        return null;
    }
clear ()
Definition at line 144 of file simple_html_dom.php.
References children(), and parent().
Referenced by __destruct().
    {
        $this->dom = null;
        $this->nodes = null;
        $this->parent = null;
        $this->children = null;
    }
convert_text ($text)
Definition at line 764 of file simple_html_dom.php.
References is_utf8().
Referenced by __get(), outertext(), and text().
    {
        global $debugObject;
        if (is_object($debugObject)) {$debugObject->debugLogEntry(1);}
        $converted_text = $text;
        $sourceCharset = "";
        $targetCharset = "";
        if ($this->dom)
        {
            $sourceCharset = strtoupper($this->dom->_charset);
            $targetCharset = strtoupper($this->dom->_target_charset);
        }
        if (is_object($debugObject)) {$debugObject->debugLog(3, "source charset: " . $sourceCharset . "
       target charaset: " . $targetCharset);}
        if (!empty($sourceCharset) && !empty($targetCharset) && (strcasecmp($sourceCharset, $targetCharset)
       != 0))
        {
            // Check if the reported encoding could have been incorrect and the text is actually already
       UTF-8
            if ((strcasecmp($targetCharset, 'UTF-8') == 0) && ($this->is_utf8($text)))
            {
                $converted_text = $text;
            }
            else
            {
                $converted_text = iconv($sourceCharset, $targetCharset, $text);
            }
        }
        // Lets make sure that we don't have that silly BOM issue with any of the utf-8 text we output.
        if ($targetCharset == 'UTF-8')
        {
            if (substr($converted_text, 0, 3) == "\xef\xbb\xbf")
            {
                $converted_text = substr($converted_text, 3);
            }
            if (substr($converted_text, -3) == "\xef\xbb\xbf")
            {
                $converted_text = substr($converted_text, 0, -3);
            }
        }
        return $converted_text;
    }
dump ($show_attr = true, $deep = 0)
Definition at line 153 of file simple_html_dom.php.
    {
        $lead = str_repeat(' ', $deep);
        echo $lead.$this->tag;
        if ($show_attr && count($this->attr)>0)
        {
            echo '(';
            foreach ($this->attr as $k=>$v)
                echo "[$k]=>\"".$this->$k.'", ';
            echo ')';
        }
        echo "\n";
        if ($this->nodes)
        {
            foreach ($this->nodes as $c)
            {
                $c->dump($show_attr, $deep+1);
            }
        }
    }
dump_node ($echo = true)
Definition at line 178 of file simple_html_dom.php.
References $tag, $tag_start, children(), HDOM_INFO_INNER, and text().
    {
        $string = $this->tag;
        if (count($this->attr)>0)
        {
            $string .= '(';
            foreach ($this->attr as $k=>$v)
            {
                $string .= "[$k]=>\"".$this->$k.'", ';
            }
            $string .= ')';
        }
        if (count($this->_)>0)
        {
            $string .= ' $_ (';
            foreach ($this->_ as $k=>$v)
            {
                if (is_array($v))
                {
                    $string .= "[$k]=>(";
                    foreach ($v as $k2=>$v2)
                    {
                        $string .= "[$k2]=>\"".$v2.'", ';
                    }
                    $string .= ")";
                } else {
                    $string .= "[$k]=>\"".$v.'", ';
                }
            }
            $string .= ")";
        }
        if (isset($this->text))
        {
            $string .= " text: (" . $this->text . ")";
        }
        $string .= " HDOM_INNER_INFO: '";
        if (isset($node->_[HDOM_INFO_INNER]))
        {
            $string .= $node->_[HDOM_INFO_INNER] . "'";
        }
        else
        {
            $string .= ' NULL ';
        }
        $string .= " children: " . count($this->children);
        $string .= " nodes: " . count($this->nodes);
        $string .= " tag_start: " . $this->tag_start;
        $string .= "\n";
        if ($echo)
        {
            echo $string;
            return;
        }
        else
        {
            return $string;
        }
    }
find ($selector, $idx = null, $lowercase = false)
Definition at line 502 of file simple_html_dom.php.
References HDOM_INFO_BEGIN, and parse_selector().
Referenced by getElementById(), getElementByTagName(), getElementsById(), and getElementsByTagName().
    {
        $selectors = $this->parse_selector($selector);
        if (($count=count($selectors))===0) return array();
        $found_keys = array();
        // find each selector
        for ($c=0; $c<$count; ++$c)
        {
            // The change on the below line was documented on the sourceforge code tracker id 2788009
            // used to be: if (($levle=count($selectors[0]))===0) return array();
            if (($levle=count($selectors[$c]))===0) return array();
            if (!isset($this->_[HDOM_INFO_BEGIN])) return array();
            $head = array($this->_[HDOM_INFO_BEGIN]=>1);
            // handle descendant selectors, no recursive!
            for ($l=0; $l<$levle; ++$l)
            {
                $ret = array();
                foreach ($head as $k=>$v)
                {
                    $n = ($k===-1) ? $this->dom->root : $this->dom->nodes[$k];
                    //PaperG - Pass this optional parameter on to the seek function.
                    $n->seek($selectors[$c][$l], $ret, $lowercase);
                }
                $head = $ret;
            }
            foreach ($head as $k=>$v)
            {
                if (!isset($found_keys[$k]))
                    $found_keys[$k] = 1;
            }
        }
        // sort keys
        ksort($found_keys);
        $found = array();
        foreach ($found_keys as $k=>$v)
            $found[] = $this->dom->nodes[$k];
        // return nth-element or array
        if (is_null($idx)) return $found;
        else if ($idx<0) $idx = count($found) + $idx;
        return (isset($found[$idx])) ? $found[$idx] : null;
    }
find_ancestor_tag ($tag)
Definition at line 329 of file simple_html_dom.php.
References $tag.
    {
        global $debugObject;
        if (is_object($debugObject)) { $debugObject->debugLogEntry(1); }
        // Start by including ourselves in the comparison.
        $returnDom = $this;
        while (!is_null($returnDom))
        {
            if (is_object($debugObject)) { $debugObject->debugLog(2, "Current tag is: " . $returnDom->tag);
       }
            if ($returnDom->tag == $tag)
            {
                break;
            }
            $returnDom = $returnDom->parent;
        }
        return $returnDom;
    }
first_child ()
Definition at line 276 of file simple_html_dom.php.
References children().
Referenced by firstChild().
    {
        if (count($this->children)>0)
        {
            return $this->children[0];
        }
        return null;
    }
firstChild ()
Definition at line 953 of file simple_html_dom.php.
References first_child().
{return $this->first_child();}
get_display_size ()
Function to try a few tricks to determine the displayed size of an img on the page. NOTE: This will ONLY work on an IMG tag. Returns FALSE on all other tag types.
Author
John Schlick
Version
April 19 2012
Returns
array an array containing the 'height' and 'width' of the image on the page or -1 if we can't figure it out.
Definition at line 861 of file simple_html_dom.php.
    {
        global $debugObject;
        $width = -1;
        $height = -1;
        if ($this->tag !== 'img')
        {
            return false;
        }
        // See if there is aheight or width attribute in the tag itself.
        if (isset($this->attr['width']))
        {
            $width = $this->attr['width'];
        }
        if (isset($this->attr['height']))
        {
            $height = $this->attr['height'];
        }
        // Now look for an inline style.
        if (isset($this->attr['style']))
        {
            // Thanks to user gnarf from stackoverflow for this regular expression.
            $attributes = array();
            preg_match_all("/([\w-]+)\s*:\s*([^;]+)\s*;?/", $this->attr['style'], $matches, PREG_SET_ORDER)
      ;
            foreach ($matches as $match) {
              $attributes[$match[1]] = $match[2];
            }
            // If there is a width in the style attributes:
            if (isset($attributes['width']) && $width == -1)
            {
                // check that the last two characters are px (pixels)
                if (strtolower(substr($attributes['width'], -2)) == 'px')
                {
                    $proposed_width = substr($attributes['width'], 0, -2);
                    // Now make sure that it's an integer and not something stupid.
                    if (filter_var($proposed_width, FILTER_VALIDATE_INT))
                    {
                        $width = $proposed_width;
                    }
                }
            }
            // If there is a width in the style attributes:
            if (isset($attributes['height']) && $height == -1)
            {
                // check that the last two characters are px (pixels)
                if (strtolower(substr($attributes['height'], -2)) == 'px')
                {
                    $proposed_height = substr($attributes['height'], 0, -2);
                    // Now make sure that it's an integer and not something stupid.
                    if (filter_var($proposed_height, FILTER_VALIDATE_INT))
                    {
                        $height = $proposed_height;
                    }
                }
            }
        }
        // Future enhancement:
        // Look in the tag to see if there is a class or id specified that has a height or width attribute
       to it.
        // Far future enhancement
        // Look at all the parent tags of this image to see if they specify a class or id that has an img
       selector that specifies a height or width
        // Note that in this case, the class or id will have the img subselector for it to apply to the
       image.
        // ridiculously far future development
        // If the class or id is specified in a SEPARATE css file thats not on the page, go get it and do
       what we were just doing for the ones on the page.
        $result = array('height' => $height,
                        'width' => $width);
        return $result;
    }
getAllAttributes ()
Definition at line 942 of file simple_html_dom.php.
References $attr.
{return $this->attr;}
getAttribute ($name)
Definition at line 943 of file simple_html_dom.php.
References __get().
{return $this->__get($name);}
getElementById ($id)
Definition at line 947 of file simple_html_dom.php.
References find().
{return $this->find("#$id", 0);}
getElementByTagName ($name)
Definition at line 949 of file simple_html_dom.php.
References find().
{return $this->find($name, 0);}
getElementsById ($id, $idx = null)
Definition at line 948 of file simple_html_dom.php.
References find().
{return $this->find("#$id", $idx);}
getElementsByTagName ($name, $idx = null)
Definition at line 950 of file simple_html_dom.php.
References find().
{return $this->find($name, $idx);}
has_child ()
Definition at line 259 of file simple_html_dom.php.
References children().
Referenced by hasChildNodes().
    {
        return !empty($this->children);
    }
hasAttribute ($name)
Definition at line 945 of file simple_html_dom.php.
References __isset().
{return $this->__isset($name);}
hasChildNodes ()
Definition at line 957 of file simple_html_dom.php.
References has_child().
{return $this->has_child();}
innertext ()
Definition at line 351 of file simple_html_dom.php.
References HDOM_INFO_INNER, and HDOM_INFO_TEXT.
Referenced by __get(), outertext(), and xmltext().
    {
        if (isset($this->_[HDOM_INFO_INNER])) return $this->_[
      HDOM_INFO_INNER];
        if (isset($this->_[HDOM_INFO_TEXT])) return $this->dom->restore_noise($this->_[
      HDOM_INFO_TEXT]);
        $ret = '';
        foreach ($this->nodes as $n)
            $ret .= $n->outertext();
        return $ret;
    }
static is_utf8 ($str) [static]
Returns true if $string is valid UTF-8 and false otherwise.
Parameters
mixed $str String to be tested
Returns
boolean
Definition at line 816 of file simple_html_dom.php.
Referenced by convert_text().
    {
        $c=0; $b=0;
        $bits=0;
        $len=strlen($str);
        for($i=0; $i<$len; $i++)
        {
            $c=ord($str[$i]);
            if($c > 128)
            {
                if(($c >= 254)) return false;
                elseif($c >= 252) $bits=6;
                elseif($c >= 248) $bits=5;
                elseif($c >= 240) $bits=4;
                elseif($c >= 224) $bits=3;
                elseif($c >= 192) $bits=2;
                else return false;
                if(($i+$bits) > $len) return false;
                while($bits > 1)
                {
                    $i++;
                    $b=ord($str[$i]);
                    if($b < 128 || $b > 191) return false;
                    $bits--;
                }
            }
        }
        return true;
    }
last_child ()
Definition at line 286 of file simple_html_dom.php.
References children().
Referenced by lastChild().
    {
        if (($count=count($this->children))>0)
        {
            return $this->children[$count-1];
        }
        return null;
    }
lastChild ()
Definition at line 954 of file simple_html_dom.php.
References last_child().
{return $this->last_child();}
makeup ()
Definition at line 466 of file simple_html_dom.php.
References HDOM_INFO_ENDSPACE, HDOM_INFO_QUOTE, HDOM_INFO_SPACE, HDOM_INFO_TEXT, HDOM_QUOTE_DOUBLE, and HDOM_QUOTE_SINGLE.
    {
        // text, comment, unknown
        if (isset($this->_[HDOM_INFO_TEXT])) return $this->dom->restore_noise($this->_[
      HDOM_INFO_TEXT]);
        $ret = '<'.$this->tag;
        $i = -1;
        foreach ($this->attr as $key=>$val)
        {
            ++$i;
            // skip removed attribute
            if ($val===null || $val===false)
                continue;
            $ret .= $this->_[HDOM_INFO_SPACE][$i][0];
            //no value attr: nowrap, checked selected...
            if ($val===true)
                $ret .= $key;
            else {
                switch ($this->_[HDOM_INFO_QUOTE][$i])
                {
                    case HDOM_QUOTE_DOUBLE: $quote = '"'; break;
                    case HDOM_QUOTE_SINGLE: $quote = '\''; break;
                    default: $quote = '';
                }
                $ret .= $key.$this->_[HDOM_INFO_SPACE][$i][1].'='.$this->_[
      HDOM_INFO_SPACE][$i][2].$quote.$val.$quote;
            }
        }
        $ret = $this->dom->restore_noise($ret);
        return $ret . $this->_[HDOM_INFO_ENDSPACE] . '>';
    }
match ($exp, $pattern, $value) [protected]
Definition at line 650 of file simple_html_dom.php.
Referenced by seek().
                                                     {
        global $debugObject;
        if (is_object($debugObject)) {$debugObject->debugLogEntry(1);}
        switch ($exp) {
            case '=':
                return ($value===$pattern);
            case '!=':
                return ($value!==$pattern);
            case '^=':
                return preg_match("/^".preg_quote($pattern,'/')."/", $value);
            case '$=':
                return preg_match("/".preg_quote($pattern,'/')."$/", $value);
            case '*=':
                if ($pattern[0]=='/') {
                    return preg_match($pattern, $value);
                }
                return preg_match("/".$pattern."/i", $value);
        }
        return false;
    }
next_sibling ()
Definition at line 296 of file simple_html_dom.php.
References parent().
Referenced by nextSibling().
    {
        if ($this->parent===null)
        {
            return null;
        }
        $idx = 0;
        $count = count($this->parent->children);
        while ($idx<$count && $this!==$this->parent->children[$idx])
        {
            ++$idx;
        }
        if (++$idx>=$count)
        {
            return null;
        }
        return $this->parent->children[$idx];
    }
nextSibling ()
Definition at line 955 of file simple_html_dom.php.
References next_sibling().
{return $this->next_sibling();}
nodeName ()
Definition at line 958 of file simple_html_dom.php.
References $tag.
{return $this->tag;}
outertext ()
Definition at line 363 of file simple_html_dom.php.
References convert_text(), HDOM_INFO_BEGIN, HDOM_INFO_END, HDOM_INFO_INNER, HDOM_INFO_OUTER, HDOM_INFO_TEXT, innertext(), and text().
Referenced by __get(), and __toString().
    {
        global $debugObject;
        if (is_object($debugObject))
        {
            $text = '';
            if ($this->tag == 'text')
            {
                if (!empty($this->text))
                {
                    $text = " with text: " . $this->text;
                }
            }
            $debugObject->debugLog(1, 'Innertext of tag: ' . $this->tag . $text);
        }
        if ($this->tag==='root') return $this->innertext();
        // trigger callback
        if ($this->dom && $this->dom->callback!==null)
        {
            call_user_func_array($this->dom->callback, array($this));
        }
        if (isset($this->_[HDOM_INFO_OUTER])) return $this->_[
      HDOM_INFO_OUTER];
        if (isset($this->_[HDOM_INFO_TEXT])) return $this->dom->restore_noise($this->_[
      HDOM_INFO_TEXT]);
        // render begin tag
        if ($this->dom && $this->dom->nodes[$this->_[HDOM_INFO_BEGIN]])
        {
            $ret = $this->dom->nodes[$this->_[HDOM_INFO_BEGIN]]->makeup();
        } else {
            $ret = "";
        }
        // render inner text
        if (isset($this->_[HDOM_INFO_INNER]))
        {
            // If it's a br tag... don't return the HDOM_INNER_INFO that we may or may not have added.
            if ($this->tag != "br")
            {
                $ret .= $this->_[HDOM_INFO_INNER];
            }
        } else {
            if ($this->nodes)
            {
                foreach ($this->nodes as $n)
                {
                    $ret .= $this->convert_text($n->outertext());
                }
            }
        }
        // render end tag
        if (isset($this->_[HDOM_INFO_END]) && $this->_[
      HDOM_INFO_END]!=0)
            $ret .= '</'.$this->tag.'>';
        return $ret;
    }
parent ($parent = null)
Definition at line 244 of file simple_html_dom.php.
References $parent.
Referenced by clear(), next_sibling(), parentNode(), and prev_sibling().
    {
        // I am SURE that this doesn't work properly.
        // It fails to unset the current node from it's current parents nodes or children list first.
        if ($parent !== null)
        {
            $this->parent = $parent;
            $this->parent->nodes[] = $this;
            $this->parent->children[] = $this;
        }
        return $this->parent;
    }
parentNode ()
Definition at line 951 of file simple_html_dom.php.
References parent().
{return $this->parent();}
parse_selector ($selector_string) [protected]
Definition at line 672 of file simple_html_dom.php.
References $tag.
Referenced by find().
                                                        {
        global $debugObject;
        if (is_object($debugObject)) {$debugObject->debugLogEntry(1);}
        // pattern of CSS selectors, modified from mootools
        // Paperg: Add the colon to the attrbute, so that it properly finds <tag attr:ibute="something" >
       like google does.
        // Note: if you try to look at this attribute, yo MUST use getAttribute since $dom->x:y will fail
       the php syntax check.
// Notice the \[ starting the attbute? and the @? following? This implies that an attribute can begin
       with an @ sign that is not captured.
// This implies that an html attribute specifier may start with an @ sign that is NOT captured by the
       expression.
// farther study is required to determine of this should be documented or removed.
// $pattern =
       "/([\w-:\*]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w-]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is";
        $pattern = "/([\w-:\*]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"
      ']?)?\])?([\/, ]+)/is";
        preg_match_all($pattern, trim($selector_string).' ', $matches, PREG_SET_ORDER);
        if (is_object($debugObject)) {$debugObject->debugLog(2, "Matches Array: ", $matches);}
        $selectors = array();
        $result = array();
        //print_r($matches);
        foreach ($matches as $m) {
            $m[0] = trim($m[0]);
            if ($m[0]==='' || $m[0]==='/' || $m[0]==='//') continue;
            // for browser generated xpath
            if ($m[1]==='tbody') continue;
            list($tag, $key, $val, $exp, $no_key) = array($m[1], null, null, '=', false);
            if (!empty($m[2])) {$key='id'; $val=$m[2];}
            if (!empty($m[3])) {$key='class'; $val=$m[3];}
            if (!empty($m[4])) {$key=$m[4];}
            if (!empty($m[5])) {$exp=$m[5];}
            if (!empty($m[6])) {$val=$m[6];}
            // convert to lowercase
            if ($this->dom->lowercase) {$tag=strtolower($tag); $key=strtolower($key);}
            //elements that do NOT have the specified attribute
            if (isset($key[0]) && $key[0]==='!') {$key=substr($key, 1); $no_key=true;}
            $result[] = array($tag, $key, $val, $exp, $no_key);
            if (trim($m[7])===',') {
                $selectors[] = $result;
                $result = array();
            }
        }
        if (count($result)>0)
            $selectors[] = $result;
        return $selectors;
    }
prev_sibling ()
Definition at line 317 of file simple_html_dom.php.
References parent().
Referenced by previousSibling().
    {
        if ($this->parent===null) return null;
        $idx = 0;
        $count = count($this->parent->children);
        while ($idx<$count && $this!==$this->parent->children[$idx])
            ++$idx;
        if (--$idx<0) return null;
        return $this->parent->children[$idx];
    }
previousSibling ()
Definition at line 956 of file simple_html_dom.php.
References prev_sibling().
{return $this->prev_sibling();}
removeAttribute ($name)
Definition at line 946 of file simple_html_dom.php.
References __set().
{$this->__set($name, null);}
seek ($selector, & $ret, $lowercase = false) [protected]
Definition at line 553 of file simple_html_dom.php.
References $parent, $tag, children(), HDOM_INFO_BEGIN, HDOM_INFO_END, and match().
    {
        global $debugObject;
        if (is_object($debugObject)) { $debugObject->debugLogEntry(1); }
        list($tag, $key, $val, $exp, $no_key) = $selector;
        // xpath index
        if ($tag && $key && is_numeric($key))
        {
            $count = 0;
            foreach ($this->children as $c)
            {
                if ($tag==='*' || $tag===$c->tag) {
                    if (++$count==$key) {
                        $ret[$c->_[HDOM_INFO_BEGIN]] = 1;
                        return;
                    }
                }
            }
            return;
        }
        $end = (!empty($this->_[HDOM_INFO_END])) ? $this->_[
      HDOM_INFO_END] : 0;
        if ($end==0) {
            $parent = $this->parent;
            while (!isset($parent->_[HDOM_INFO_END]) &&
      $parent!==null) {
                $end -= 1;
                $parent = $parent->parent;
            }
            $end += $parent->_[HDOM_INFO_END];
        }
        for ($i=$this->_[HDOM_INFO_BEGIN]+1; $i<$end; ++$i) {
            $node = $this->dom->nodes[$i];
            $pass = true;
            if ($tag==='*' && !$key) {
                if (in_array($node, $this->children, true))
                    $ret[$i] = 1;
                continue;
            }
            // compare tag
            if ($tag && $tag!=$node->tag && $tag!=='*') {$pass=false;}
            // compare key
            if ($pass && $key) {
                if ($no_key) {
                    if (isset($node->attr[$key])) $pass=false;
                } else {
                    if (($key != "plaintext") && !isset($node->attr[$key])) $pass=false;
                }
            }
            // compare value
            if ($pass && $key && $val && $val!=='*') {
                // If they have told us that this is a "plaintext" search then we want the plaintext of the
       node - right?
                if ($key == "plaintext") {
                    // $node->plaintext actually returns $node->text();
                    $nodeKeyValue = $node->text();
                } else {
                    // this is a normal search, we want the value of that attribute of the tag.
                    $nodeKeyValue = $node->attr[$key];
                }
                if (is_object($debugObject)) {$debugObject->debugLog(2, "testing node: " . $node->tag . "
       for attribute: " . $key . $exp . $val . " where nodes value is: " . $nodeKeyValue);}
                //PaperG - If lowercase is set, do a case insensitive test of the value of the selector.
                if ($lowercase) {
                    $check = $this->match($exp, strtolower($val), strtolower($nodeKeyValue));
                } else {
                    $check = $this->match($exp, $val, $nodeKeyValue);
                }
                if (is_object($debugObject)) {$debugObject->debugLog(2, "after match: " . ($check ? "true"
      : "false"));}
                // handle multiple class
                if (!$check && strcasecmp($key, 'class')===0) {
                    foreach (explode(' ',$node->attr[$key]) as $k) {
                        // Without this, there were cases where leading, trailing, or double spaces lead to
       our comparing blanks - bad form.
                        if (!empty($k)) {
                            if ($lowercase) {
                                $check = $this->match($exp, strtolower($val), strtolower($k));
                            } else {
                                $check = $this->match($exp, $val, $k);
                            }
                            if ($check) break;
                        }
                    }
                }
                if (!$check) $pass = false;
            }
            if ($pass) $ret[$i] = 1;
            unset($node);
        }
        // It's passed by reference so this is actually what this function returns.
        if (is_object($debugObject)) {$debugObject->debugLog(1, "EXIT - ret: ", $ret);}
    }
setAttribute ($name, $value)
Definition at line 944 of file simple_html_dom.php.
References __set().
{$this->__set($name, $value);}
text ()
Definition at line 423 of file simple_html_dom.php.
References convert_text(), HDOM_INFO_INNER, HDOM_INFO_TEXT, HDOM_TYPE_COMMENT, HDOM_TYPE_TEXT, and HDOM_TYPE_UNKNOWN.
Referenced by __get(), dump_node(), and outertext().
    {
        if (isset($this->_[HDOM_INFO_INNER])) return $this->_[
      HDOM_INFO_INNER];
        switch ($this->nodetype)
        {
            case HDOM_TYPE_TEXT: return $this->dom->restore_noise($this->_[
      HDOM_INFO_TEXT]);
            case HDOM_TYPE_COMMENT: return '';
            case HDOM_TYPE_UNKNOWN: return '';
        }
        if (strcasecmp($this->tag, 'script')===0) return '';
        if (strcasecmp($this->tag, 'style')===0) return '';
        $ret = '';
        // In rare cases, (always node type 1 or HDOM_TYPE_ELEMENT - observed for some span tags, and some
       p tags) $this->nodes is set to NULL.
        // NOTE: This indicates that there is a problem where it's set to NULL without a clear happening.
        // WHY is this happening?
        if (!is_null($this->nodes))
        {
            foreach ($this->nodes as $n)
            {
                $ret .= $this->convert_text($n->text());
            }
            // If this node is a span... add a space at the end of it so multiple spans don't run into each
       other. This is plaintext after all.
            if ($this->tag == "span")
            {
                $ret .= $this->dom->default_span_text;
            }
        }
        return $ret;
    }
xmltext ()
Definition at line 457 of file simple_html_dom.php.
References innertext().
Referenced by __get().
    {
        $ret = $this->innertext();
        $ret = str_ireplace('<![CDATA[', '', $ret);
        $ret = str_replace(']]>', '', $ret);
        return $ret;
    }
Field Documentation
$_ = array()
Definition at line 123 of file simple_html_dom.php.
$attr = array()
Definition at line 118 of file simple_html_dom.php.
Referenced by getAllAttributes().
$children = array()
Definition at line 119 of file simple_html_dom.php.
Referenced by children().
$nodes = array()
Definition at line 120 of file simple_html_dom.php.
$nodetype = HDOM_TYPE_TEXT
Definition at line 116 of file simple_html_dom.php.
$parent = null
Definition at line 121 of file simple_html_dom.php.
Referenced by parent(), and seek().
$tag = 'text'
Definition at line 117 of file simple_html_dom.php.
Referenced by dump_node(), find_ancestor_tag(), nodeName(), parse_selector(), and seek().
$tag_start = 0
Definition at line 124 of file simple_html_dom.php.
Referenced by dump_node().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mvc-framework/application/libraries/simple_html_dom.php